<a href="https://colab.research.google.com/github/shagunsingla15-cloud/Iris-dataset/blob/main/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split
X = df.drop('species',axis = 1)
y = df['species']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
model_knn = KNeighborsClassifier(n_neighbors = 5)
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [9]:
model_knn.score(X_test,y_test)

0.98

In [10]:
from sklearn.svm import SVC
model_svm = SVC(gamma = 'auto', C =30, kernel = 'rbf') # C VALUE IS HERE A PUNISHMENT

In [11]:
model_svm.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [12]:
model_svm.score(X_test,y_test)

0.98

# now lets use the Grid search cv

In [13]:
from sklearn.model_selection import GridSearchCV

In [14]:
classifier = GridSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel': ['rbf','linear'],
}, cv =5, return_train_score = False)

In [15]:
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [16]:
classifier.cv_results_

{'mean_fit_time': array([0.00270905, 0.0025454 , 0.00223622, 0.00211768, 0.00223007,
        0.00206871, 0.00216994, 0.00368376]),
 'std_fit_time': array([4.76420545e-04, 6.84161318e-04, 1.51920349e-05, 3.21705743e-05,
        1.27487977e-04, 2.66369790e-05, 8.28946257e-05, 1.83588523e-04]),
 'mean_score_time': array([0.00235415, 0.00168076, 0.00170546, 0.00156479, 0.00163875,
        0.00157318, 0.00162911, 0.00261831]),
 'std_score_time': array([1.11851860e-03, 1.07522561e-04, 4.72536722e-05, 3.87881163e-05,
        7.49873393e-05, 4.60812232e-05, 6.93087361e-05, 1.05346700e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [17]:
results = pd.DataFrame(classifier.cv_results_)

In [18]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002709,0.000476,0.002354,0.001119,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002545,0.000684,0.001681,0.000108,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002236,0.000015,0.001705,0.000047,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002118,0.000032,0.001565,0.000039,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002230,0.000127,0.001639,0.000075,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.002069,0.000027,0.001573,0.000046,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002170,0.000083,0.001629,0.000069,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.003684,0.000184,0.002618,0.000105,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [19]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

for knn

In [20]:
classifier2 = GridSearchCV((model_knn),{
    'n_neighbors': [3,5,10,15],
    'weights': ['uniform','distance'],
    'algorithm': ['auto','ball_tree','kd_tree','brute']
}, cv =5, return_train_score = False)

In [21]:
classifier2.fit(X, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [3, 5, 10, 15],
                         'weights': ['uniform', 'distance']})

In [22]:
result2_knn = pd.DataFrame(classifier2.cv_results_)

In [23]:
result2_knn[['param_n_neighbors','param_algorithm','param_weights','mean_test_score']]

    param_n_neighbors param_algorithm param_weights  mean_test_score
0                   3            auto       uniform         0.966667
1                   3            auto      distance         0.966667
2                   5            auto       uniform         0.973333
3                   5            auto      distance         0.966667
4                  10            auto       uniform         0.980000
5                  10            auto      distance         0.986667
6                  15            auto       uniform         0.966667
7                  15            auto      distance         0.973333
8                   3       ball_tree       uniform         0.966667
9                   3       ball_tree      distance         0.966667
10                  5       ball_tree       uniform         0.973333
11                  5       ball_tree      distance         0.966667
12                 10       ball_tree       uniform         0.980000
13                 10       ball_tree      distance         0.986667
14                 15       ball_tree       uniform         0.966667
15                 15       ball_tree      distance         0.973333
16                  3         kd_tree       uniform         0.966667
17                  3         kd_tree      distance         0.966667
18                  5         kd_tree       uniform         0.973333
19                  5         kd_tree      distance         0.966667
20                 10         kd_tree       uniform         0.980000
21                 10         kd_tree      distance         0.986667
22                 15         kd_tree       uniform         0.966667
23                 15         kd_tree      distance         0.973333
24                  3           brute       uniform         0.966667
25                  3           brute      distance         0.966667
26                  5           brute       uniform         0.973333
27                  5           brute      distance         0.966667
28                 10           brute       uniform         0.986667
29                 10           brute      distance         0.986667
30                 15           brute       uniform         0.966667
31                 15           brute      distance         0.973333

# *Stacking*

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

In [25]:
X = df.drop('species',axis = 1)
y = df['species']

In [26]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42, stratify= y_encoded)

In [28]:
base_learners = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svc',SVC(probability=True, kernel = 'rbf',random_state=42)),
    ('lr', LogisticRegression(max_iter= 1000))
]

In [29]:
meta_learner = LogisticRegression(max_iter=1000)

In [30]:
stacking_clf = StackingClassifier(
    estimators = base_learners,
    final_estimator = meta_learner,
    cv =5
)

In [31]:
stacking_clf.fit(X_train, y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svc', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [32]:
y_pred = stacking_clf.predict(X_test)

In [33]:
accuracy = accuracy_score(y_test,y_pred)

In [34]:
accuracy

0.9666666666666667

# Random forest (bagging)

In [35]:
from sklearn.ensemble import RandomForestClassifier

In [36]:
rf_model = RandomForestClassifier(
    n_estimators = 100 ,   # number of tree
    max_depth = None ,     # lets trees grow fully
    random_state= 42
)

In [37]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [38]:
y_pred = rf_model.predict(X_test)

In [39]:
accuracy_rf = accuracy_score(y_test,y_pred)

In [40]:
accuracy_rf

0.9

# *Boosting*

**ADABOOST**

In [42]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier

In [45]:
ada_model = AdaBoostClassifier(n_estimators = 100 , random_state = 42)

In [46]:
ada_model.fit(X_train,y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [47]:
y_pred = ada_model.predict(X_test)

In [48]:
accuracy_ada = accuracy_score(y_test,y_pred)

In [49]:
accuracy_ada

0.9333333333333333

In [50]:
gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate = 0.1,random_state =42)

In [51]:
gb_model.fit(X_train,y_train)

GradientBoostingClassifier(random_state=42)

In [52]:
y_pred = gb_model.predict(X_test)

In [53]:
accuracy_gb = accuracy_score(y_test, y_pred)

In [54]:
accuracy_gb

0.9666666666666667

In [56]:
xgb_model = XGBClassifier(n_estimators = 100, learing_rate=0.1, max_depth = 3, use_label_encoder = False, eval_matric= 'mlogloss', random_state =42)

In [57]:
xgb_model.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [14:18:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:794:
Parameters: { "eval_matric", "learing_rate", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_matric='mlogloss', eval_metric=None,
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learing_rate=0.1,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100, ...)

In [58]:
y_pred = xgb_model.predict(X_test)

In [60]:
accuracy_XGB = accuracy_score(y_test,y_pred)

In [61]:
accuracy_XGB

0.9333333333333333