In [48]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [49]:
df = sns.load_dataset('iris')

In [50]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [51]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [52]:
from sklearn.model_selection import train_test_split
X = df.drop('species',axis = 1)
y = df['species']

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [54]:
from sklearn.neighbors import KNeighborsClassifier

In [55]:
model_knn = KNeighborsClassifier(n_neighbors = 5)
model_knn.fit(X_train,y_train)

KNeighborsClassifier()

In [56]:
model_knn.score(X_test,y_test)

0.98

In [57]:
from sklearn.svm import SVC
model_svm = SVC(gamma = 'auto', C =30, kernel = 'rbf') # C VALUE IS HERE A PUNISHMENT

In [58]:
model_svm.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [59]:
model_svm.score(X_test,y_test)

0.98

# now lets use the Grid search cv

In [60]:
from sklearn.model_selection import GridSearchCV

In [61]:
classifier = GridSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel': ['rbf','linear'],
}, cv =5, return_train_score = False)

In [62]:
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [63]:
classifier.cv_results_

{'mean_fit_time': array([0.00380797, 0.0023005 , 0.0023591 , 0.00222812, 0.00230808,
        0.00216012, 0.00228028, 0.00221949]),
 'std_fit_time': array([1.12790993e-03, 4.87146979e-05, 6.42013734e-05, 4.08250587e-05,
        6.56882603e-05, 4.05579086e-05, 4.76845264e-05, 5.91742041e-05]),
 'mean_score_time': array([0.00301824, 0.00180125, 0.00173101, 0.00165863, 0.00179372,
        0.0016696 , 0.0017139 , 0.00167675]),
 'std_score_time': array([1.06843870e-03, 4.22844609e-05, 5.62396226e-05, 5.38795183e-05,
        1.18948327e-04, 3.82289601e-05, 3.05025242e-05, 3.29043208e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [64]:
results = pd.DataFrame(classifier.cv_results_)

In [65]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003808,0.001128,0.003018,0.001068,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002301,0.000049,0.001801,0.000042,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002359,0.000064,0.001731,0.000056,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002228,0.000041,0.001659,0.000054,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002308,0.000066,0.001794,0.000119,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.002160,0.000041,0.001670,0.000038,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002280,0.000048,0.001714,0.000031,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002219,0.000059,0.001677,0.000033,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [66]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

for knn

In [67]:
classifier2 = GridSearchCV((model_knn),{
    'n_neighbors': [3,5,10,15],
    'weights': ['uniform','distance'],
    'algorithm': ['auto','ball_tree','kd_tree','brute']
}, cv =5, return_train_score = False)

In [68]:
classifier2.fit(X, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [3, 5, 10, 15],
                         'weights': ['uniform', 'distance']})

In [69]:
result2_knn = pd.DataFrame(classifier2.cv_results_)

In [70]:
result2_knn[['param_n_neighbors','param_algorithm','param_weights','mean_test_score']]

    param_n_neighbors param_algorithm param_weights  mean_test_score
0                   3            auto       uniform         0.966667
1                   3            auto      distance         0.966667
2                   5            auto       uniform         0.973333
3                   5            auto      distance         0.966667
4                  10            auto       uniform         0.980000
5                  10            auto      distance         0.986667
6                  15            auto       uniform         0.966667
7                  15            auto      distance         0.973333
8                   3       ball_tree       uniform         0.966667
9                   3       ball_tree      distance         0.966667
10                  5       ball_tree       uniform         0.973333
11                  5       ball_tree      distance         0.966667
12                 10       ball_tree       uniform         0.980000
13                 10       ball_tree      distance         0.986667
14                 15       ball_tree       uniform         0.966667
15                 15       ball_tree      distance         0.973333
16                  3         kd_tree       uniform         0.966667
17                  3         kd_tree      distance         0.966667
18                  5         kd_tree       uniform         0.973333
19                  5         kd_tree      distance         0.966667
20                 10         kd_tree       uniform         0.980000
21                 10         kd_tree      distance         0.986667
22                 15         kd_tree       uniform         0.966667
23                 15         kd_tree      distance         0.973333
24                  3           brute       uniform         0.966667
25                  3           brute      distance         0.966667
26                  5           brute       uniform         0.973333
27                  5           brute      distance         0.966667
28                 10           brute       uniform         0.986667
29                 10           brute      distance         0.986667
30                 15           brute       uniform         0.966667
31                 15           brute      distance         0.973333

# *Stacking*

In [75]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

In [73]:
X = df.drop('species',axis = 1)
y = df['species']

In [77]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [78]:
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42, stratify= y_encoded)

In [79]:
base_learners = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svc',SVC(probability=True, kernel = 'rbf',random_state=42)),
    ('lr', LogisticRegression(max_iter= 1000))
]

In [82]:
meta_learner = LogisticRegression(max_iter=1000)

In [83]:
stacking_clf = StackingClassifier(
    estimators = base_learners,
    final_estimator = meta_learner,
    cv =5
)

In [84]:
stacking_clf.fit(X_train, y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svc', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [85]:
y_pred = stacking_clf.predict(X_test)

In [86]:
accuracy = accuracy_score(y_test,y_pred)

In [87]:
accuracy

0.9666666666666667